# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='書籍名')),
                ('lunch', models.IntegerField(blank=True, default=0, verbose_name='昼予算')),
                ('dinner', models.IntegerField(blank=True, default=0, verbose_name='夜予算')),
                ('point', models.FloatField(blank=True, default=0, verbose_name='点数')),
                ('review', models.IntegerField(blank=True, default=0, verbose_name='口コミ')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
                ('holiday', models.CharField(max_length=255, verbose_name='休日')),
                ('station', models.CharField(max_length=255, verbose_name='最寄駅')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='カテゴリ')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Shop')),
            ],
        ),
    ]
