# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_auto_20170216_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='コメント')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ポイント')),
            ],
        ),
        migrations.CreateModel(
            name='ShopPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Point')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='shoppoint',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Shop'),
        ),
        migrations.AddField(
            model_name='comment',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Shop'),
        ),
    ]
